[package]
name = "twitch-irc-rs"
version = "0.1.0"
authors = ["Ruben Anders <ruben.anders@robotty.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"
maplit = "1.0.2"
derive_more = "0.99.2"
pin-project = "0.4.6"
async-trait = "0.1.22"
thiserror = "1.0.9"
futures = "0.3.1"
tokio-util = { version = "0.3.1", features = ["codec"] }
bytes = "0.5.3"
tungstenite = "0.11.0"
async-tungstenite = { version = "0.6.0", features = ["tokio-runtime", "tokio-native-tls"] }
url = "2.1.1"
smallvec = "1.1.0"
log = "0.4.8"
env_logger = "0.7.1"
derivative = "2.1.1"
tokio = { version = "0.2.21", features = ["rt-core", "time", "tcp", "sync", "io-util", "macros"] }
tokio-native-tls = "0.1.0"
native-tls = "0.2.4"
enum_dispatch = "0.3.1"

[lib]
name = "twitch_irc"
path = "src/lib.rs"

[[bin]]
name = "twitch_irc_demo"
path = "src/main.rs"
