name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update Rust
      run: rustup update
    - name: Build
      run: cargo build --all-features --examples --tests
    - name: Run tests
      run: cargo test
    - name: Check format
      run: cargo fmt -- --check
